import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Page(props) {
	console.log(props)
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>{props.slug}</h1>
				<div>{props.time} <button><a href="/api/revalidate?slug=/test_revalidate">Revalidate</a></button></div>
			</main>
		</div>
	)
}

export async function getStaticProps(context) {
	return {
		props: {
			slug: context.params.slug.join('/'),
			time: Date.now()
		}
	}
}

export async function getStaticPaths(context) {
	return {
		paths: [],
		fallback: 'blocking'
	}
}

