import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home(props) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>Preview: {props.preview}</h1>
				<div>{props.time} <button><a href="/api/revalidate?slug=/">Revalidate</a></button></div>
			</main>
		</div>
	)
}

export async function getStaticProps(context) {
	return {
		props: {
			time: Date.now(),
			preview: context.preview ? 'true' : 'false'
		}
	}
}

